# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=30)),
                ('ac_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_option', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=30)),
                ('pr_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name1', models.CharField(max_length=30)),
                ('last_name2', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='pr_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.User'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='p_enc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.Rubrica'),
        ),
        migrations.AddField(
            model_name='participante',
            name='par_projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.Pregunta'),
        ),
        migrations.AddField(
            model_name='participante',
            name='par_userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.User'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='o_preg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.Pregunta'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='eq_projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.Pregunta'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ac_projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PT.Project'),
        ),
    ]
